// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: device/v1/device.proto

package devicev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DispatchCommandRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeviceCommandId string                 `protobuf:"bytes,1,opt,name=device_command_id,json=deviceCommandId,proto3" json:"device_command_id,omitempty"`
	FeedRequestId   string                 `protobuf:"bytes,2,opt,name=feed_request_id,json=feedRequestId,proto3" json:"feed_request_id,omitempty"`
	DeviceId        string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	RoomId          string                 `protobuf:"bytes,4,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	AmountGrams     uint32                 `protobuf:"varint,5,opt,name=amount_grams,json=amountGrams,proto3" json:"amount_grams,omitempty"`
	MotorDurationMs uint32                 `protobuf:"varint,6,opt,name=motor_duration_ms,json=motorDurationMs,proto3" json:"motor_duration_ms,omitempty"`
	ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DispatchCommandRequest) Reset() {
	*x = DispatchCommandRequest{}
	mi := &file_device_v1_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchCommandRequest) ProtoMessage() {}

func (x *DispatchCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchCommandRequest.ProtoReflect.Descriptor instead.
func (*DispatchCommandRequest) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{0}
}

func (x *DispatchCommandRequest) GetDeviceCommandId() string {
	if x != nil {
		return x.DeviceCommandId
	}
	return ""
}

func (x *DispatchCommandRequest) GetFeedRequestId() string {
	if x != nil {
		return x.FeedRequestId
	}
	return ""
}

func (x *DispatchCommandRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DispatchCommandRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *DispatchCommandRequest) GetAmountGrams() uint32 {
	if x != nil {
		return x.AmountGrams
	}
	return 0
}

func (x *DispatchCommandRequest) GetMotorDurationMs() uint32 {
	if x != nil {
		return x.MotorDurationMs
	}
	return 0
}

func (x *DispatchCommandRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type DispatchCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchCommandResponse) Reset() {
	*x = DispatchCommandResponse{}
	mi := &file_device_v1_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchCommandResponse) ProtoMessage() {}

func (x *DispatchCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchCommandResponse.ProtoReflect.Descriptor instead.
func (*DispatchCommandResponse) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{1}
}

func (x *DispatchCommandResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type ReportTelemetryRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DeviceId           string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	RemainingFoodGrams uint32                 `protobuf:"varint,2,opt,name=remaining_food_grams,json=remainingFoodGrams,proto3" json:"remaining_food_grams,omitempty"`
	BatteryPercent     uint32                 `protobuf:"varint,3,opt,name=battery_percent,json=batteryPercent,proto3" json:"battery_percent,omitempty"`
	FirmwareVersion    string                 `protobuf:"bytes,4,opt,name=firmware_version,json=firmwareVersion,proto3" json:"firmware_version,omitempty"`
	ReportedAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=reported_at,json=reportedAt,proto3" json:"reported_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReportTelemetryRequest) Reset() {
	*x = ReportTelemetryRequest{}
	mi := &file_device_v1_device_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTelemetryRequest) ProtoMessage() {}

func (x *ReportTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTelemetryRequest.ProtoReflect.Descriptor instead.
func (*ReportTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{2}
}

func (x *ReportTelemetryRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ReportTelemetryRequest) GetRemainingFoodGrams() uint32 {
	if x != nil {
		return x.RemainingFoodGrams
	}
	return 0
}

func (x *ReportTelemetryRequest) GetBatteryPercent() uint32 {
	if x != nil {
		return x.BatteryPercent
	}
	return 0
}

func (x *ReportTelemetryRequest) GetFirmwareVersion() string {
	if x != nil {
		return x.FirmwareVersion
	}
	return ""
}

func (x *ReportTelemetryRequest) GetReportedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReportedAt
	}
	return nil
}

type ReportTelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTelemetryResponse) Reset() {
	*x = ReportTelemetryResponse{}
	mi := &file_device_v1_device_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTelemetryResponse) ProtoMessage() {}

func (x *ReportTelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_v1_device_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTelemetryResponse.ProtoReflect.Descriptor instead.
func (*ReportTelemetryResponse) Descriptor() ([]byte, []int) {
	return file_device_v1_device_proto_rawDescGZIP(), []int{3}
}

var File_device_v1_device_proto protoreflect.FileDescriptor

const file_device_v1_device_proto_rawDesc = "" +
	"\n" +
	"\x16device/v1/device.proto\x12\x10yunmao.device.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xac\x02\n" +
	"\x16DispatchCommandRequest\x12*\n" +
	"\x11device_command_id\x18\x01 \x01(\tR\x0fdeviceCommandId\x12&\n" +
	"\x0ffeed_request_id\x18\x02 \x01(\tR\rfeedRequestId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x17\n" +
	"\aroom_id\x18\x04 \x01(\tR\x06roomId\x12!\n" +
	"\famount_grams\x18\x05 \x01(\rR\vamountGrams\x12*\n" +
	"\x11motor_duration_ms\x18\x06 \x01(\rR\x0fmotorDurationMs\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"5\n" +
	"\x17DispatchCommandResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\xf8\x01\n" +
	"\x16ReportTelemetryRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x120\n" +
	"\x14remaining_food_grams\x18\x02 \x01(\rR\x12remainingFoodGrams\x12'\n" +
	"\x0fbattery_percent\x18\x03 \x01(\rR\x0ebatteryPercent\x12)\n" +
	"\x10firmware_version\x18\x04 \x01(\tR\x0ffirmwareVersion\x12;\n" +
	"\vreported_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"reportedAt\"\x19\n" +
	"\x17ReportTelemetryResponse2\xe6\x01\n" +
	"\x14DeviceControlService\x12f\n" +
	"\x0fDispatchCommand\x12(.yunmao.device.v1.DispatchCommandRequest\x1a).yunmao.device.v1.DispatchCommandResponse\x12f\n" +
	"\x0fReportTelemetry\x12(.yunmao.device.v1.ReportTelemetryRequest\x1a).yunmao.device.v1.ReportTelemetryResponseB\xab\x01\n" +
	"\x14com.yunmao.device.v1B\vDeviceProtoP\x01Z$yunmao.live/proto/device/v1;devicev1\xa2\x02\x03YDX\xaa\x02\x10Yunmao.Device.V1\xca\x02\x10Yunmao\\Device\\V1\xe2\x02\x1cYunmao\\Device\\V1\\GPBMetadata\xea\x02\x12Yunmao::Device::V1b\x06proto3"

var (
	file_device_v1_device_proto_rawDescOnce sync.Once
	file_device_v1_device_proto_rawDescData []byte
)

func file_device_v1_device_proto_rawDescGZIP() []byte {
	file_device_v1_device_proto_rawDescOnce.Do(func() {
		file_device_v1_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_device_v1_device_proto_rawDesc), len(file_device_v1_device_proto_rawDesc)))
	})
	return file_device_v1_device_proto_rawDescData
}

var file_device_v1_device_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_device_v1_device_proto_goTypes = []any{
	(*DispatchCommandRequest)(nil),  // 0: yunmao.device.v1.DispatchCommandRequest
	(*DispatchCommandResponse)(nil), // 1: yunmao.device.v1.DispatchCommandResponse
	(*ReportTelemetryRequest)(nil),  // 2: yunmao.device.v1.ReportTelemetryRequest
	(*ReportTelemetryResponse)(nil), // 3: yunmao.device.v1.ReportTelemetryResponse
	(*timestamppb.Timestamp)(nil),   // 4: google.protobuf.Timestamp
}
var file_device_v1_device_proto_depIdxs = []int32{
	4, // 0: yunmao.device.v1.DispatchCommandRequest.expires_at:type_name -> google.protobuf.Timestamp
	4, // 1: yunmao.device.v1.ReportTelemetryRequest.reported_at:type_name -> google.protobuf.Timestamp
	0, // 2: yunmao.device.v1.DeviceControlService.DispatchCommand:input_type -> yunmao.device.v1.DispatchCommandRequest
	2, // 3: yunmao.device.v1.DeviceControlService.ReportTelemetry:input_type -> yunmao.device.v1.ReportTelemetryRequest
	1, // 4: yunmao.device.v1.DeviceControlService.DispatchCommand:output_type -> yunmao.device.v1.DispatchCommandResponse
	3, // 5: yunmao.device.v1.DeviceControlService.ReportTelemetry:output_type -> yunmao.device.v1.ReportTelemetryResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_device_v1_device_proto_init() }
func file_device_v1_device_proto_init() {
	if File_device_v1_device_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_device_v1_device_proto_rawDesc), len(file_device_v1_device_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_device_v1_device_proto_goTypes,
		DependencyIndexes: file_device_v1_device_proto_depIdxs,
		MessageInfos:      file_device_v1_device_proto_msgTypes,
	}.Build()
	File_device_v1_device_proto = out.File
	file_device_v1_device_proto_goTypes = nil
	file_device_v1_device_proto_depIdxs = nil
}
