// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: device/v1/device.proto

package devicev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeviceControlService_DispatchCommand_FullMethodName = "/yunmao.device.v1.DeviceControlService/DispatchCommand"
	DeviceControlService_ReportTelemetry_FullMethodName = "/yunmao.device.v1.DeviceControlService/ReportTelemetry"
)

// DeviceControlServiceClient is the client API for DeviceControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceControlServiceClient interface {
	DispatchCommand(ctx context.Context, in *DispatchCommandRequest, opts ...grpc.CallOption) (*DispatchCommandResponse, error)
	ReportTelemetry(ctx context.Context, in *ReportTelemetryRequest, opts ...grpc.CallOption) (*ReportTelemetryResponse, error)
}

type deviceControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceControlServiceClient(cc grpc.ClientConnInterface) DeviceControlServiceClient {
	return &deviceControlServiceClient{cc}
}

func (c *deviceControlServiceClient) DispatchCommand(ctx context.Context, in *DispatchCommandRequest, opts ...grpc.CallOption) (*DispatchCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchCommandResponse)
	err := c.cc.Invoke(ctx, DeviceControlService_DispatchCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceControlServiceClient) ReportTelemetry(ctx context.Context, in *ReportTelemetryRequest, opts ...grpc.CallOption) (*ReportTelemetryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportTelemetryResponse)
	err := c.cc.Invoke(ctx, DeviceControlService_ReportTelemetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceControlServiceServer is the server API for DeviceControlService service.
// All implementations should embed UnimplementedDeviceControlServiceServer
// for forward compatibility.
type DeviceControlServiceServer interface {
	DispatchCommand(context.Context, *DispatchCommandRequest) (*DispatchCommandResponse, error)
	ReportTelemetry(context.Context, *ReportTelemetryRequest) (*ReportTelemetryResponse, error)
}

// UnimplementedDeviceControlServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeviceControlServiceServer struct{}

func (UnimplementedDeviceControlServiceServer) DispatchCommand(context.Context, *DispatchCommandRequest) (*DispatchCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DispatchCommand not implemented")
}
func (UnimplementedDeviceControlServiceServer) ReportTelemetry(context.Context, *ReportTelemetryRequest) (*ReportTelemetryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportTelemetry not implemented")
}
func (UnimplementedDeviceControlServiceServer) testEmbeddedByValue() {}

// UnsafeDeviceControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceControlServiceServer will
// result in compilation errors.
type UnsafeDeviceControlServiceServer interface {
	mustEmbedUnimplementedDeviceControlServiceServer()
}

func RegisterDeviceControlServiceServer(s grpc.ServiceRegistrar, srv DeviceControlServiceServer) {
	// If the following call panics, it indicates UnimplementedDeviceControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeviceControlService_ServiceDesc, srv)
}

func _DeviceControlService_DispatchCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceControlServiceServer).DispatchCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceControlService_DispatchCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceControlServiceServer).DispatchCommand(ctx, req.(*DispatchCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceControlService_ReportTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportTelemetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceControlServiceServer).ReportTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceControlService_ReportTelemetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceControlServiceServer).ReportTelemetry(ctx, req.(*ReportTelemetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceControlService_ServiceDesc is the grpc.ServiceDesc for DeviceControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yunmao.device.v1.DeviceControlService",
	HandlerType: (*DeviceControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DispatchCommand",
			Handler:    _DeviceControlService_DispatchCommand_Handler,
		},
		{
			MethodName: "ReportTelemetry",
			Handler:    _DeviceControlService_ReportTelemetry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "device/v1/device.proto",
}
