/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/v1/auth/login/sms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Initiate SMS login flow */
        post: operations["startSmsLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login/sms/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete SMS login with code */
        post: operations["completeSmsLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user by ID */
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List rooms with optional filters */
        get: operations["listRooms"];
        put?: never;
        /** Create a new room */
        post: operations["createRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rooms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get room by ID */
        get: operations["getRoom"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update room fields */
        patch: operations["updateRoom"];
        trace?: never;
    };
    "/v1/rooms/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set room status (offline/live/idle) */
        post: operations["setRoomStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rooms/{id}/rotate-stream-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate stream key for a room */
        post: operations["rotateStreamKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rooms/{id}/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue a room subscription token for playback */
        post: operations["issueSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rooms/{id}/ice-servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get TURN/STUN ICE servers for WebRTC */
        get: operations["getIceServers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feed-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a feed request */
        post: operations["createFeedRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feed-requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get feed request status */
        get: operations["getFeedRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feed-requests/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a pending feed request */
        post: operations["cancelFeedRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a billing order */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get order by ID */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}/prepay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create prepay for an order */
        post: operations["createPrepay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pay/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available pay channels and their mode */
        get: operations["listPayChannels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallets/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user wallet balance */
        get: operations["getWallet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallets/holds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reserve a wallet hold for payment */
        post: operations["reserveHold"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallets/holds/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get wallet hold status */
        get: operations["getHold"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallets/holds/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm wallet hold (deduct funds) */
        post: operations["confirmHold"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallets/holds/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel wallet hold (release funds) */
        post: operations["cancelHold"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallets/{user_id}/topup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Top up wallet with coins */
        post: operations["topUpWallet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/rooms/{id}/feeding-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetFeedingPolicy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["adminUpdateFeedingPolicy"];
        trace?: never;
    };
    "/v1/admin/feeding-safety": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetFeedingSafety"];
        put: operations["adminPutFeedingSafety"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/feature-flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListFeatureFlags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/feature-flags/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetFeatureFlag"];
        put: operations["adminSetFeatureFlag"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/webrtc/gray-sim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminSimulateWebrtcGray"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/chat/wordlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListWordlist"];
        put: operations["adminPutWordlist"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/chat/wordlist/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetWordlistVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/wallets/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetWallet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/wallets/holds/{hold_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetWalletHold"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/{room_id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["chatListMessages"];
        put?: never;
        post: operations["chatSendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/chat/messages/{id}/moderate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["chatModerateMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["deviceList"];
        put?: never;
        post: operations["deviceRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["deviceGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["deviceUpdate"];
        trace?: never;
    };
    "/api/v1/devices/{id}/bind": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deviceBindRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/unbind": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deviceUnbindRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deviceSetStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/mqtt-credential": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deviceIssueMqttCredential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/firmware": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deviceUpdateFirmware"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/last-feed-request/{feedId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["deviceGetLastFeedRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        Error: {
            code: string;
            message: string;
            trace_id?: string;
        };
        StartSmsLoginRequest: {
            /**
             * @description E.164 phone number
             * @example +8613800138000
             */
            phone: string;
        };
        SmsChallengeResponse: {
            /** Format: uuid */
            challenge_id: string;
            /** @description Debug only, absent in production */
            sms_code?: string;
            expires_in_seconds: number;
        };
        CompleteSmsLoginRequest: {
            /** Format: uuid */
            challenge_id: string;
            code: string;
        };
        LoginResponse: {
            access_token: string;
            user: components["schemas"]["User"];
        };
        AuthToken: {
            token: string;
            /** Format: uuid */
            user_id: string;
            /** Format: int64 */
            expires_at: number;
        };
        User: {
            /** Format: uuid */
            id: string;
            phone_e164: string;
            nickname?: string;
            /** Format: uri */
            avatar_url?: string;
            roles?: string[];
            /** Format: date-time */
            created_at?: string;
        };
        Room: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            status: "offline" | "live" | "idle";
            /** Format: uuid */
            owner_id: string;
            cover?: string;
            /** Format: uri */
            cover_url?: string;
            region_id?: string;
            /** @enum {string} */
            protocol_pref?: "hls" | "webrtc";
            webrtc_eligible?: boolean;
            stream_key?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        RoomListResponse: {
            rooms: components["schemas"]["Room"][];
            total?: number;
            next_offset?: number;
        };
        CreateRoomRequest: {
            name: string;
            /** Format: uuid */
            owner_id: string;
            region_id?: string;
        };
        UpdateRoomRequest: {
            name?: string;
            /** Format: uri */
            cover_url?: string;
        };
        SetStatusRequest: {
            /** @enum {string} */
            status: "offline" | "live" | "idle";
        };
        IdStatusResponse: {
            /** Format: uuid */
            id: string;
            status: string;
        };
        RotateStreamKeyResponse: {
            /** Format: uuid */
            id: string;
            stream_key: string;
        };
        RoomSubscription: {
            /** Format: uuid */
            room_id: string;
            token: string;
            /** Format: uri */
            url_playback: string;
            /** Format: uri */
            url_whep?: string;
            webrtc_enabled?: boolean;
        };
        IceServersResponse: {
            ice_servers: components["schemas"]["IceServer"][];
            /** Format: int64 */
            expires_at: number;
        };
        IceServer: {
            urls: string[];
            username?: string;
            credential?: string;
        };
        CreateFeedRequest: {
            /** Format: uuid */
            room_id: string;
            /** Format: uuid */
            user_id: string;
            grams: number;
            feed_ticket_id: string;
            idempotency_key: string;
        };
        FeedRequest: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "pending" | "queued" | "dispensing" | "completed" | "failed" | "timeout" | "cancelled";
            /** Format: uuid */
            room_id: string;
            /** Format: uuid */
            user_id: string;
            grams: number;
            feed_ticket_id?: string;
            idempotency_key?: string;
            /** Format: uri */
            cam_record_url?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        FeedResponse: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "pending" | "queued" | "dispensing" | "completed" | "failed" | "timeout" | "cancelled";
            /** Format: uri */
            cam_record_url?: string;
        };
        CancelFeedRequest: {
            reason?: string;
        };
        CreateOrderRequest: {
            /** Format: uuid */
            user_id: string;
            amount_cny: number;
            subject: string;
        };
        Order: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            amount_cny: number;
            /** @enum {string} */
            status: "pending" | "paid" | "refunded" | "failed" | "expired";
            subject?: string;
            channel?: string;
            external_trade_no?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            paid_at?: string;
        };
        CreatePrepayRequest: {
            /** Format: int64 */
            amount_fen: number;
            subject: string;
        };
        PrepayResponse: {
            /** @enum {string} */
            channel: "wechatpay" | "alipay" | "appleiap" | "mock";
            prepay_id: string;
            /** Format: uri */
            pay_url?: string;
            qr_content?: string;
            client_hints?: {
                [key: string]: string;
            };
        };
        PayChannelsResponse: {
            channels: components["schemas"]["PayChannelInfo"][];
        };
        PayChannelInfo: {
            name: string;
            /** @enum {string} */
            mode: "mock" | "real";
        };
        Wallet: {
            /** Format: uuid */
            user_id: string;
            /** Format: int64 */
            balance_fen: number;
            coins: number;
        };
        ReserveHoldRequest: {
            /** Format: uuid */
            user_id: string;
            /** Format: int64 */
            amount_fen: number;
            /** Format: uuid */
            order_id?: string;
            reason?: string;
        };
        WalletHold: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            /** Format: int64 */
            amount_fen: number;
            /** @enum {string} */
            status: "held" | "confirmed" | "cancelled" | "expired";
            /** Format: uuid */
            order_id?: string;
            reason?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            expires_at?: string;
        };
        ChatMessage: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            room_id: string;
            /** Format: uuid */
            user_id: string;
            nickname?: string;
            body: string;
            /** Format: int64 */
            created_at: number;
            /** @enum {string} */
            moderation?: "ok" | "hide" | "review";
        };
        AdminFeedingPolicy: {
            feeding_open: boolean;
            feed_cooldown_seconds: number;
            user_room_cooldown_seconds: number;
            no_feed_window_start?: string;
            no_feed_window_end?: string;
            daily_limit_grams: number;
        };
        AdminSafetyDTO: {
            room_cooldown_sec: number;
            user_room_cooldown_sec: number;
            cat_daily_limit: number;
        };
        AdminFeatureFlag: {
            name: string;
            enabled: boolean;
            scope?: string;
            value?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            updated_at?: string;
            updated_by?: string;
        };
        AdminWordlistEntry: {
            region?: string;
            language?: string;
            word: string;
            /** @enum {string} */
            action: "hide" | "review" | "ban";
        };
        AdminWordlistImportRequest: {
            entries: components["schemas"]["AdminWordlistEntry"][];
            updated_by?: string;
        };
        AdminWordlistImportResponse: {
            version: number;
            applied: number;
        };
        AdminWebrtcGraySimResult: {
            flag?: string;
            enabled?: boolean;
            samples?: number;
            hit_webrtc?: number;
            hit_pct?: number;
            configured_gray_pct?: number;
        };
        AdminWalletBalance: {
            UserID?: string;
            BalanceFen?: number;
            ReservedFen?: number;
            RegionID?: string;
            /** Format: date-time */
            UpdatedAt?: string;
        };
        ChatSendRequest: {
            user_id?: string;
            body: string;
            emojis?: string[];
            client_msg_id?: string;
        };
        ChatModerateRequest: {
            /** @enum {string} */
            status: "pending" | "published" | "hidden" | "deleted" | "flagged" | "recall" | "warn" | "mute";
            reason?: string;
        };
        Device: {
            id: string;
            owner_id: string;
            room_id?: string;
            region_id?: string;
            firmware?: string;
            hardware_model?: string;
            /** @enum {string} */
            status?: "online" | "offline" | "error";
            /** Format: date-time */
            last_heartbeat_at?: string;
        };
        DeviceActionResponse: {
            id: string;
            room_id?: string;
            status?: string;
            target?: string;
        };
        MqttCredential: {
            device_id: string;
            username: string;
            password: string;
            /** Format: date-time */
            expires_at: string;
            algorithm?: string;
            key_kid?: string;
        };
        DeviceLastFeedRequest: {
            feed_request_id?: string;
            status?: string;
            device_id?: string;
            room_id?: string;
            amount_grams?: number;
        };
    };
    responses: {
        /** @description Malformed request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid authentication */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Idempotency or state conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    startSmsLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartSmsLoginRequest"];
            };
        };
        responses: {
            /** @description SMS challenge issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmsChallengeResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    completeSmsLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteSmsLoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listRooms: {
        parameters: {
            query?: {
                owner_id?: string;
                region_id?: string;
                status?: "offline" | "live" | "idle";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Room list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomListResponse"];
                };
            };
        };
    };
    createRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoomRequest"];
            };
        };
        responses: {
            /** @description Room created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Room"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Room found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Room"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoomRequest"];
            };
        };
        responses: {
            /** @description Room updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Room"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    setRoomStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetStatusRequest"];
            };
        };
        responses: {
            /** @description Status updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdStatusResponse"];
                };
            };
        };
    };
    rotateStreamKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New stream key issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotateStreamKeyResponse"];
                };
            };
        };
    };
    issueSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription token issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomSubscription"];
                };
            };
        };
    };
    getIceServers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ICE server config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IceServersResponse"];
                };
            };
        };
    };
    createFeedRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFeedRequest"];
            };
        };
        responses: {
            /** @description Feed request accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedRequest"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    getFeedRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Feed request status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedRequest"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    cancelFeedRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CancelFeedRequest"];
            };
        };
        responses: {
            /** @description Feed request cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedRequest"];
                };
            };
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description Order created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createPrepay: {
        parameters: {
            query?: {
                channel?: "wechatpay" | "alipay" | "appleiap" | "mock";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePrepayRequest"];
            };
        };
        responses: {
            /** @description Prepay created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrepayResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listPayChannels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Channel list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayChannelsResponse"];
                };
            };
        };
    };
    getWallet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wallet info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wallet"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    reserveHold: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReserveHoldRequest"];
            };
        };
        responses: {
            /** @description Hold created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletHold"];
                };
            };
        };
    };
    getHold: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hold info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletHold"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    confirmHold: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hold confirmed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletHold"];
                };
            };
        };
    };
    cancelHold: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description Hold cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletHold"];
                };
            };
        };
    };
    topUpWallet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: int64 */
                    amount_fen: number;
                };
            };
        };
        responses: {
            /** @description Top up successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                    };
                };
            };
        };
    };
    adminGetFeedingPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Room feeding policy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminFeedingPolicy"];
                };
            };
        };
    };
    adminUpdateFeedingPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminFeedingPolicy"];
            };
        };
        responses: {
            /** @description Policy updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminGetFeedingSafety: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Global feeding safety limits */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSafetyDTO"];
                };
            };
        };
    };
    adminPutFeedingSafety: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminSafetyDTO"];
            };
        };
        responses: {
            /** @description Global safety updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminListFeatureFlags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Feature flag list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminFeatureFlag"][];
                };
            };
        };
    };
    adminGetFeatureFlag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Feature flag */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminFeatureFlag"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    adminSetFeatureFlag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminFeatureFlag"];
            };
        };
        responses: {
            /** @description Flag updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminFeatureFlag"];
                };
            };
            /** @description Flag updated (no content fallback) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminSimulateWebrtcGray: {
        parameters: {
            query?: {
                room_count?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gray release simulation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminWebrtcGraySimResult"];
                };
            };
        };
    };
    adminListWordlist: {
        parameters: {
            query?: {
                region?: string;
                language?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wordlist entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        entries: components["schemas"]["AdminWordlistEntry"][];
                    };
                };
            };
        };
    };
    adminPutWordlist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminWordlistImportRequest"];
            };
        };
        responses: {
            /** @description Wordlist imported */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminWordlistImportResponse"];
                };
            };
        };
    };
    adminGetWordlistVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wordlist version number */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        version?: number;
                    };
                };
            };
        };
    };
    adminGetWallet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wallet balance (proxy) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminWalletBalance"];
                };
            };
        };
    };
    adminGetWalletHold: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hold_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wallet hold (proxy) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletHold"];
                };
            };
        };
    };
    chatListMessages: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessage"][];
                };
            };
        };
    };
    chatSendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatSendRequest"];
            };
        };
        responses: {
            /** @description Message sent */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessage"];
                };
            };
        };
    };
    chatModerateMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatModerateRequest"];
            };
        };
        responses: {
            /** @description Message moderated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessage"];
                };
            };
        };
    };
    deviceList: {
        parameters: {
            query?: {
                owner_id?: string;
                room_id?: string;
                region_id?: string;
                status?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        devices: components["schemas"]["Device"][];
                    };
                };
            };
        };
    };
    deviceRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Device"];
            };
        };
        responses: {
            /** @description Device registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
        };
    };
    deviceGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deviceUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Device"];
            };
        };
        responses: {
            /** @description Device updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
        };
    };
    deviceBindRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    room_id: string;
                };
            };
        };
        responses: {
            /** @description Device bound */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceActionResponse"];
                };
            };
        };
    };
    deviceUnbindRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device unbound */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceActionResponse"];
                };
            };
        };
    };
    deviceSetStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "online" | "offline" | "error";
                };
            };
        };
        responses: {
            /** @description Status set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceActionResponse"];
                };
            };
        };
    };
    deviceIssueMqttCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description MQTT credentials issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MqttCredential"];
                };
            };
        };
    };
    deviceUpdateFirmware: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    target: string;
                };
            };
        };
        responses: {
            /** @description Firmware update initiated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceActionResponse"];
                };
            };
        };
    };
    deviceGetLastFeedRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                feedId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Last feed request for device */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceLastFeedRequest"];
                };
            };
        };
    };
}
