// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: feeding/v1/feeding.proto

package feedingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FeedingService_ValidateAndCreate_FullMethodName = "/yunmao.feeding.v1.FeedingService/ValidateAndCreate"
	FeedingService_GetFeedRequest_FullMethodName    = "/yunmao.feeding.v1.FeedingService/GetFeedRequest"
)

// FeedingServiceClient is the client API for FeedingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FeedingService 内部 gRPC 接口（参见 04-设备接入数据模型与API边界.md 第 6 节）。
//
// MVP 阶段只列出最核心的几个 RPC，schema 兼容向前演进。
type FeedingServiceClient interface {
	// 校验并创建投喂请求；返回创建的 FeedRequest 与冷却信息。
	ValidateAndCreate(ctx context.Context, in *ValidateAndCreateRequest, opts ...grpc.CallOption) (*ValidateAndCreateResponse, error)
	// 查询投喂请求当前状态。
	GetFeedRequest(ctx context.Context, in *GetFeedRequestRequest, opts ...grpc.CallOption) (*FeedRequest, error)
}

type feedingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFeedingServiceClient(cc grpc.ClientConnInterface) FeedingServiceClient {
	return &feedingServiceClient{cc}
}

func (c *feedingServiceClient) ValidateAndCreate(ctx context.Context, in *ValidateAndCreateRequest, opts ...grpc.CallOption) (*ValidateAndCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateAndCreateResponse)
	err := c.cc.Invoke(ctx, FeedingService_ValidateAndCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedingServiceClient) GetFeedRequest(ctx context.Context, in *GetFeedRequestRequest, opts ...grpc.CallOption) (*FeedRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedRequest)
	err := c.cc.Invoke(ctx, FeedingService_GetFeedRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeedingServiceServer is the server API for FeedingService service.
// All implementations should embed UnimplementedFeedingServiceServer
// for forward compatibility.
//
// FeedingService 内部 gRPC 接口（参见 04-设备接入数据模型与API边界.md 第 6 节）。
//
// MVP 阶段只列出最核心的几个 RPC，schema 兼容向前演进。
type FeedingServiceServer interface {
	// 校验并创建投喂请求；返回创建的 FeedRequest 与冷却信息。
	ValidateAndCreate(context.Context, *ValidateAndCreateRequest) (*ValidateAndCreateResponse, error)
	// 查询投喂请求当前状态。
	GetFeedRequest(context.Context, *GetFeedRequestRequest) (*FeedRequest, error)
}

// UnimplementedFeedingServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFeedingServiceServer struct{}

func (UnimplementedFeedingServiceServer) ValidateAndCreate(context.Context, *ValidateAndCreateRequest) (*ValidateAndCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateAndCreate not implemented")
}
func (UnimplementedFeedingServiceServer) GetFeedRequest(context.Context, *GetFeedRequestRequest) (*FeedRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFeedRequest not implemented")
}
func (UnimplementedFeedingServiceServer) testEmbeddedByValue() {}

// UnsafeFeedingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeedingServiceServer will
// result in compilation errors.
type UnsafeFeedingServiceServer interface {
	mustEmbedUnimplementedFeedingServiceServer()
}

func RegisterFeedingServiceServer(s grpc.ServiceRegistrar, srv FeedingServiceServer) {
	// If the following call panics, it indicates UnimplementedFeedingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FeedingService_ServiceDesc, srv)
}

func _FeedingService_ValidateAndCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateAndCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedingServiceServer).ValidateAndCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedingService_ValidateAndCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedingServiceServer).ValidateAndCreate(ctx, req.(*ValidateAndCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedingService_GetFeedRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedingServiceServer).GetFeedRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedingService_GetFeedRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedingServiceServer).GetFeedRequest(ctx, req.(*GetFeedRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FeedingService_ServiceDesc is the grpc.ServiceDesc for FeedingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FeedingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yunmao.feeding.v1.FeedingService",
	HandlerType: (*FeedingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateAndCreate",
			Handler:    _FeedingService_ValidateAndCreate_Handler,
		},
		{
			MethodName: "GetFeedRequest",
			Handler:    _FeedingService_GetFeedRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feeding/v1/feeding.proto",
}
