// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: feeding/v1/feeding.proto

package feedingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeedRequest_Status int32

const (
	FeedRequest_STATUS_UNSPECIFIED FeedRequest_Status = 0
	FeedRequest_CREATED            FeedRequest_Status = 1
	FeedRequest_REJECTED           FeedRequest_Status = 2
	FeedRequest_ACCEPTED           FeedRequest_Status = 3
	FeedRequest_QUEUED             FeedRequest_Status = 4
	FeedRequest_DISPATCHED         FeedRequest_Status = 5
	FeedRequest_ACKNOWLEDGED       FeedRequest_Status = 6
	FeedRequest_SUCCEEDED          FeedRequest_Status = 7
	FeedRequest_FAILED             FeedRequest_Status = 8
	FeedRequest_COMPENSATED        FeedRequest_Status = 9
)

// Enum value maps for FeedRequest_Status.
var (
	FeedRequest_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "CREATED",
		2: "REJECTED",
		3: "ACCEPTED",
		4: "QUEUED",
		5: "DISPATCHED",
		6: "ACKNOWLEDGED",
		7: "SUCCEEDED",
		8: "FAILED",
		9: "COMPENSATED",
	}
	FeedRequest_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"CREATED":            1,
		"REJECTED":           2,
		"ACCEPTED":           3,
		"QUEUED":             4,
		"DISPATCHED":         5,
		"ACKNOWLEDGED":       6,
		"SUCCEEDED":          7,
		"FAILED":             8,
		"COMPENSATED":        9,
	}
)

func (x FeedRequest_Status) Enum() *FeedRequest_Status {
	p := new(FeedRequest_Status)
	*p = x
	return p
}

func (x FeedRequest_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeedRequest_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_feeding_v1_feeding_proto_enumTypes[0].Descriptor()
}

func (FeedRequest_Status) Type() protoreflect.EnumType {
	return &file_feeding_v1_feeding_proto_enumTypes[0]
}

func (x FeedRequest_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeedRequest_Status.Descriptor instead.
func (FeedRequest_Status) EnumDescriptor() ([]byte, []int) {
	return file_feeding_v1_feeding_proto_rawDescGZIP(), []int{2, 0}
}

type ValidateAndCreateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoomId         string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	AmountGrams    uint32                 `protobuf:"varint,3,opt,name=amount_grams,json=amountGrams,proto3" json:"amount_grams,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// 客户端可选：把客户端时间戳带上，便于排障
	ClientTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAndCreateRequest) Reset() {
	*x = ValidateAndCreateRequest{}
	mi := &file_feeding_v1_feeding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAndCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAndCreateRequest) ProtoMessage() {}

func (x *ValidateAndCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feeding_v1_feeding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAndCreateRequest.ProtoReflect.Descriptor instead.
func (*ValidateAndCreateRequest) Descriptor() ([]byte, []int) {
	return file_feeding_v1_feeding_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateAndCreateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateAndCreateRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ValidateAndCreateRequest) GetAmountGrams() uint32 {
	if x != nil {
		return x.AmountGrams
	}
	return 0
}

func (x *ValidateAndCreateRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ValidateAndCreateRequest) GetClientTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ClientTime
	}
	return nil
}

type ValidateAndCreateResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	FeedRequest *FeedRequest           `protobuf:"bytes,1,opt,name=feed_request,json=feedRequest,proto3" json:"feed_request,omitempty"`
	// 当 status = REJECTED 时填，code 为 04 章错误码
	RejectCode    string `protobuf:"bytes,2,opt,name=reject_code,json=rejectCode,proto3" json:"reject_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAndCreateResponse) Reset() {
	*x = ValidateAndCreateResponse{}
	mi := &file_feeding_v1_feeding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAndCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAndCreateResponse) ProtoMessage() {}

func (x *ValidateAndCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feeding_v1_feeding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAndCreateResponse.ProtoReflect.Descriptor instead.
func (*ValidateAndCreateResponse) Descriptor() ([]byte, []int) {
	return file_feeding_v1_feeding_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateAndCreateResponse) GetFeedRequest() *FeedRequest {
	if x != nil {
		return x.FeedRequest
	}
	return nil
}

func (x *ValidateAndCreateResponse) GetRejectCode() string {
	if x != nil {
		return x.RejectCode
	}
	return ""
}

type FeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedRequestId string                 `protobuf:"bytes,1,opt,name=feed_request_id,json=feedRequestId,proto3" json:"feed_request_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	AmountGrams   uint32                 `protobuf:"varint,5,opt,name=amount_grams,json=amountGrams,proto3" json:"amount_grams,omitempty"`
	Status        FeedRequest_Status     `protobuf:"varint,6,opt,name=status,proto3,enum=yunmao.feeding.v1.FeedRequest_Status" json:"status,omitempty"`
	RejectReason  string                 `protobuf:"bytes,7,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedRequest) Reset() {
	*x = FeedRequest{}
	mi := &file_feeding_v1_feeding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedRequest) ProtoMessage() {}

func (x *FeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feeding_v1_feeding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedRequest.ProtoReflect.Descriptor instead.
func (*FeedRequest) Descriptor() ([]byte, []int) {
	return file_feeding_v1_feeding_proto_rawDescGZIP(), []int{2}
}

func (x *FeedRequest) GetFeedRequestId() string {
	if x != nil {
		return x.FeedRequestId
	}
	return ""
}

func (x *FeedRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FeedRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *FeedRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *FeedRequest) GetAmountGrams() uint32 {
	if x != nil {
		return x.AmountGrams
	}
	return 0
}

func (x *FeedRequest) GetStatus() FeedRequest_Status {
	if x != nil {
		return x.Status
	}
	return FeedRequest_STATUS_UNSPECIFIED
}

func (x *FeedRequest) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *FeedRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FeedRequest) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type GetFeedRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedRequestId string                 `protobuf:"bytes,1,opt,name=feed_request_id,json=feedRequestId,proto3" json:"feed_request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedRequestRequest) Reset() {
	*x = GetFeedRequestRequest{}
	mi := &file_feeding_v1_feeding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedRequestRequest) ProtoMessage() {}

func (x *GetFeedRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feeding_v1_feeding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedRequestRequest.ProtoReflect.Descriptor instead.
func (*GetFeedRequestRequest) Descriptor() ([]byte, []int) {
	return file_feeding_v1_feeding_proto_rawDescGZIP(), []int{3}
}

func (x *GetFeedRequestRequest) GetFeedRequestId() string {
	if x != nil {
		return x.FeedRequestId
	}
	return ""
}

var File_feeding_v1_feeding_proto protoreflect.FileDescriptor

const file_feeding_v1_feeding_proto_rawDesc = "" +
	"\n" +
	"\x18feeding/v1/feeding.proto\x12\x11yunmao.feeding.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd5\x01\n" +
	"\x18ValidateAndCreateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12!\n" +
	"\famount_grams\x18\x03 \x01(\rR\vamountGrams\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12;\n" +
	"\vclient_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"clientTime\"\x7f\n" +
	"\x19ValidateAndCreateResponse\x12A\n" +
	"\ffeed_request\x18\x01 \x01(\v2\x1e.yunmao.feeding.v1.FeedRequestR\vfeedRequest\x12\x1f\n" +
	"\vreject_code\x18\x02 \x01(\tR\n" +
	"rejectCode\"\xab\x04\n" +
	"\vFeedRequest\x12&\n" +
	"\x0ffeed_request_id\x18\x01 \x01(\tR\rfeedRequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\x12!\n" +
	"\famount_grams\x18\x05 \x01(\rR\vamountGrams\x12=\n" +
	"\x06status\x18\x06 \x01(\x0e2%.yunmao.feeding.v1.FeedRequest.StatusR\x06status\x12#\n" +
	"\rreject_reason\x18\a \x01(\tR\frejectReason\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fcompleted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\xa3\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aCREATED\x10\x01\x12\f\n" +
	"\bREJECTED\x10\x02\x12\f\n" +
	"\bACCEPTED\x10\x03\x12\n" +
	"\n" +
	"\x06QUEUED\x10\x04\x12\x0e\n" +
	"\n" +
	"DISPATCHED\x10\x05\x12\x10\n" +
	"\fACKNOWLEDGED\x10\x06\x12\r\n" +
	"\tSUCCEEDED\x10\a\x12\n" +
	"\n" +
	"\x06FAILED\x10\b\x12\x0f\n" +
	"\vCOMPENSATED\x10\t\"?\n" +
	"\x15GetFeedRequestRequest\x12&\n" +
	"\x0ffeed_request_id\x18\x01 \x01(\tR\rfeedRequestId2\xdc\x01\n" +
	"\x0eFeedingService\x12n\n" +
	"\x11ValidateAndCreate\x12+.yunmao.feeding.v1.ValidateAndCreateRequest\x1a,.yunmao.feeding.v1.ValidateAndCreateResponse\x12Z\n" +
	"\x0eGetFeedRequest\x12(.yunmao.feeding.v1.GetFeedRequestRequest\x1a\x1e.yunmao.feeding.v1.FeedRequestB\xb3\x01\n" +
	"\x15com.yunmao.feeding.v1B\fFeedingProtoP\x01Z&yunmao.live/proto/feeding/v1;feedingv1\xa2\x02\x03YFX\xaa\x02\x11Yunmao.Feeding.V1\xca\x02\x11Yunmao\\Feeding\\V1\xe2\x02\x1dYunmao\\Feeding\\V1\\GPBMetadata\xea\x02\x13Yunmao::Feeding::V1b\x06proto3"

var (
	file_feeding_v1_feeding_proto_rawDescOnce sync.Once
	file_feeding_v1_feeding_proto_rawDescData []byte
)

func file_feeding_v1_feeding_proto_rawDescGZIP() []byte {
	file_feeding_v1_feeding_proto_rawDescOnce.Do(func() {
		file_feeding_v1_feeding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feeding_v1_feeding_proto_rawDesc), len(file_feeding_v1_feeding_proto_rawDesc)))
	})
	return file_feeding_v1_feeding_proto_rawDescData
}

var file_feeding_v1_feeding_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_feeding_v1_feeding_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_feeding_v1_feeding_proto_goTypes = []any{
	(FeedRequest_Status)(0),           // 0: yunmao.feeding.v1.FeedRequest.Status
	(*ValidateAndCreateRequest)(nil),  // 1: yunmao.feeding.v1.ValidateAndCreateRequest
	(*ValidateAndCreateResponse)(nil), // 2: yunmao.feeding.v1.ValidateAndCreateResponse
	(*FeedRequest)(nil),               // 3: yunmao.feeding.v1.FeedRequest
	(*GetFeedRequestRequest)(nil),     // 4: yunmao.feeding.v1.GetFeedRequestRequest
	(*timestamppb.Timestamp)(nil),     // 5: google.protobuf.Timestamp
}
var file_feeding_v1_feeding_proto_depIdxs = []int32{
	5, // 0: yunmao.feeding.v1.ValidateAndCreateRequest.client_time:type_name -> google.protobuf.Timestamp
	3, // 1: yunmao.feeding.v1.ValidateAndCreateResponse.feed_request:type_name -> yunmao.feeding.v1.FeedRequest
	0, // 2: yunmao.feeding.v1.FeedRequest.status:type_name -> yunmao.feeding.v1.FeedRequest.Status
	5, // 3: yunmao.feeding.v1.FeedRequest.created_at:type_name -> google.protobuf.Timestamp
	5, // 4: yunmao.feeding.v1.FeedRequest.completed_at:type_name -> google.protobuf.Timestamp
	1, // 5: yunmao.feeding.v1.FeedingService.ValidateAndCreate:input_type -> yunmao.feeding.v1.ValidateAndCreateRequest
	4, // 6: yunmao.feeding.v1.FeedingService.GetFeedRequest:input_type -> yunmao.feeding.v1.GetFeedRequestRequest
	2, // 7: yunmao.feeding.v1.FeedingService.ValidateAndCreate:output_type -> yunmao.feeding.v1.ValidateAndCreateResponse
	3, // 8: yunmao.feeding.v1.FeedingService.GetFeedRequest:output_type -> yunmao.feeding.v1.FeedRequest
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_feeding_v1_feeding_proto_init() }
func file_feeding_v1_feeding_proto_init() {
	if File_feeding_v1_feeding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feeding_v1_feeding_proto_rawDesc), len(file_feeding_v1_feeding_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_feeding_v1_feeding_proto_goTypes,
		DependencyIndexes: file_feeding_v1_feeding_proto_depIdxs,
		EnumInfos:         file_feeding_v1_feeding_proto_enumTypes,
		MessageInfos:      file_feeding_v1_feeding_proto_msgTypes,
	}.Build()
	File_feeding_v1_feeding_proto = out.File
	file_feeding_v1_feeding_proto_goTypes = nil
	file_feeding_v1_feeding_proto_depIdxs = nil
}
