// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: room/v1/room.proto

package roomv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Room struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CatId               string                 `protobuf:"bytes,2,opt,name=cat_id,json=catId,proto3" json:"cat_id,omitempty"`
	DisplayName         string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	City                string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Visibility          string                 `protobuf:"bytes,5,opt,name=visibility,proto3" json:"visibility,omitempty"`                            // public/private/audit
	LiveStatus          string                 `protobuf:"bytes,6,opt,name=live_status,json=liveStatus,proto3" json:"live_status,omitempty"`          // online/offline/maintenance
	FeedingStatus       string                 `protobuf:"bytes,7,opt,name=feeding_status,json=feedingStatus,proto3" json:"feeding_status,omitempty"` // open/closed
	FeedCooldownSeconds uint32                 `protobuf:"varint,8,opt,name=feed_cooldown_seconds,json=feedCooldownSeconds,proto3" json:"feed_cooldown_seconds,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_room_v1_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{0}
}

func (x *Room) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Room) GetCatId() string {
	if x != nil {
		return x.CatId
	}
	return ""
}

func (x *Room) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Room) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Room) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *Room) GetLiveStatus() string {
	if x != nil {
		return x.LiveStatus
	}
	return ""
}

func (x *Room) GetFeedingStatus() string {
	if x != nil {
		return x.FeedingStatus
	}
	return ""
}

func (x *Room) GetFeedCooldownSeconds() uint32 {
	if x != nil {
		return x.FeedCooldownSeconds
	}
	return 0
}

func (x *Room) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomRequest) Reset() {
	*x = GetRoomRequest{}
	mi := &file_room_v1_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomRequest) ProtoMessage() {}

func (x *GetRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomRequest.ProtoReflect.Descriptor instead.
func (*GetRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{1}
}

func (x *GetRoomRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Visibility    string                 `protobuf:"bytes,1,opt,name=visibility,proto3" json:"visibility,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomsRequest) Reset() {
	*x = ListRoomsRequest{}
	mi := &file_room_v1_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomsRequest) ProtoMessage() {}

func (x *ListRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomsRequest.ProtoReflect.Descriptor instead.
func (*ListRoomsRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{2}
}

func (x *ListRoomsRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *ListRoomsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRoomsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*Room                `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomsResponse) Reset() {
	*x = ListRoomsResponse{}
	mi := &file_room_v1_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomsResponse) ProtoMessage() {}

func (x *ListRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomsResponse.ProtoReflect.Descriptor instead.
func (*ListRoomsResponse) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{3}
}

func (x *ListRoomsResponse) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *ListRoomsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type PublishEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	DataJson      []byte                 `protobuf:"bytes,3,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventRequest) Reset() {
	*x = PublishEventRequest{}
	mi := &file_room_v1_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventRequest) ProtoMessage() {}

func (x *PublishEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventRequest.ProtoReflect.Descriptor instead.
func (*PublishEventRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{4}
}

func (x *PublishEventRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PublishEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PublishEventRequest) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

type PublishEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivered     uint32                 `protobuf:"varint,1,opt,name=delivered,proto3" json:"delivered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventResponse) Reset() {
	*x = PublishEventResponse{}
	mi := &file_room_v1_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventResponse) ProtoMessage() {}

func (x *PublishEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventResponse.ProtoReflect.Descriptor instead.
func (*PublishEventResponse) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{5}
}

func (x *PublishEventResponse) GetDelivered() uint32 {
	if x != nil {
		return x.Delivered
	}
	return 0
}

var File_room_v1_room_proto protoreflect.FileDescriptor

const file_room_v1_room_proto_rawDesc = "" +
	"\n" +
	"\x12room/v1/room.proto\x12\x0eyunmao.room.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x02\n" +
	"\x04Room\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06cat_id\x18\x02 \x01(\tR\x05catId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x1e\n" +
	"\n" +
	"visibility\x18\x05 \x01(\tR\n" +
	"visibility\x12\x1f\n" +
	"\vlive_status\x18\x06 \x01(\tR\n" +
	"liveStatus\x12%\n" +
	"\x0efeeding_status\x18\a \x01(\tR\rfeedingStatus\x122\n" +
	"\x15feed_cooldown_seconds\x18\b \x01(\rR\x13feedCooldownSeconds\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\" \n" +
	"\x0eGetRoomRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"n\n" +
	"\x10ListRoomsRequest\x12\x1e\n" +
	"\n" +
	"visibility\x18\x01 \x01(\tR\n" +
	"visibility\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"g\n" +
	"\x11ListRoomsResponse\x12*\n" +
	"\x05rooms\x18\x01 \x03(\v2\x14.yunmao.room.v1.RoomR\x05rooms\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"j\n" +
	"\x13PublishEventRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1b\n" +
	"\tdata_json\x18\x03 \x01(\fR\bdataJson\"4\n" +
	"\x14PublishEventResponse\x12\x1c\n" +
	"\tdelivered\x18\x01 \x01(\rR\tdelivered2\xfb\x01\n" +
	"\vRoomService\x12?\n" +
	"\aGetRoom\x12\x1e.yunmao.room.v1.GetRoomRequest\x1a\x14.yunmao.room.v1.Room\x12P\n" +
	"\tListRooms\x12 .yunmao.room.v1.ListRoomsRequest\x1a!.yunmao.room.v1.ListRoomsResponse\x12Y\n" +
	"\fPublishEvent\x12#.yunmao.room.v1.PublishEventRequest\x1a$.yunmao.room.v1.PublishEventResponseB\x9b\x01\n" +
	"\x12com.yunmao.room.v1B\tRoomProtoP\x01Z yunmao.live/proto/room/v1;roomv1\xa2\x02\x03YRX\xaa\x02\x0eYunmao.Room.V1\xca\x02\x0eYunmao\\Room\\V1\xe2\x02\x1aYunmao\\Room\\V1\\GPBMetadata\xea\x02\x10Yunmao::Room::V1b\x06proto3"

var (
	file_room_v1_room_proto_rawDescOnce sync.Once
	file_room_v1_room_proto_rawDescData []byte
)

func file_room_v1_room_proto_rawDescGZIP() []byte {
	file_room_v1_room_proto_rawDescOnce.Do(func() {
		file_room_v1_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_room_v1_room_proto_rawDesc), len(file_room_v1_room_proto_rawDesc)))
	})
	return file_room_v1_room_proto_rawDescData
}

var file_room_v1_room_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_room_v1_room_proto_goTypes = []any{
	(*Room)(nil),                  // 0: yunmao.room.v1.Room
	(*GetRoomRequest)(nil),        // 1: yunmao.room.v1.GetRoomRequest
	(*ListRoomsRequest)(nil),      // 2: yunmao.room.v1.ListRoomsRequest
	(*ListRoomsResponse)(nil),     // 3: yunmao.room.v1.ListRoomsResponse
	(*PublishEventRequest)(nil),   // 4: yunmao.room.v1.PublishEventRequest
	(*PublishEventResponse)(nil),  // 5: yunmao.room.v1.PublishEventResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_room_v1_room_proto_depIdxs = []int32{
	6, // 0: yunmao.room.v1.Room.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: yunmao.room.v1.ListRoomsResponse.rooms:type_name -> yunmao.room.v1.Room
	1, // 2: yunmao.room.v1.RoomService.GetRoom:input_type -> yunmao.room.v1.GetRoomRequest
	2, // 3: yunmao.room.v1.RoomService.ListRooms:input_type -> yunmao.room.v1.ListRoomsRequest
	4, // 4: yunmao.room.v1.RoomService.PublishEvent:input_type -> yunmao.room.v1.PublishEventRequest
	0, // 5: yunmao.room.v1.RoomService.GetRoom:output_type -> yunmao.room.v1.Room
	3, // 6: yunmao.room.v1.RoomService.ListRooms:output_type -> yunmao.room.v1.ListRoomsResponse
	5, // 7: yunmao.room.v1.RoomService.PublishEvent:output_type -> yunmao.room.v1.PublishEventResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_room_v1_room_proto_init() }
func file_room_v1_room_proto_init() {
	if File_room_v1_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_room_v1_room_proto_rawDesc), len(file_room_v1_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_room_v1_room_proto_goTypes,
		DependencyIndexes: file_room_v1_room_proto_depIdxs,
		MessageInfos:      file_room_v1_room_proto_msgTypes,
	}.Build()
	File_room_v1_room_proto = out.File
	file_room_v1_room_proto_goTypes = nil
	file_room_v1_room_proto_depIdxs = nil
}
