// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user/v1/user.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	PhoneHash     string                 `protobuf:"bytes,3,opt,name=phone_hash,json=phoneHash,proto3" json:"phone_hash,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *User) GetPhoneHash() string {
	if x != nil {
		return x.PhoneHash
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type StartSmsLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneE164     string                 `protobuf:"bytes,1,opt,name=phone_e164,json=phoneE164,proto3" json:"phone_e164,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSmsLoginRequest) Reset() {
	*x = StartSmsLoginRequest{}
	mi := &file_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSmsLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSmsLoginRequest) ProtoMessage() {}

func (x *StartSmsLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSmsLoginRequest.ProtoReflect.Descriptor instead.
func (*StartSmsLoginRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *StartSmsLoginRequest) GetPhoneE164() string {
	if x != nil {
		return x.PhoneE164
	}
	return ""
}

type StartSmsLoginResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId      string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	ExpiresInSeconds uint32                 `protobuf:"varint,2,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StartSmsLoginResponse) Reset() {
	*x = StartSmsLoginResponse{}
	mi := &file_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSmsLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSmsLoginResponse) ProtoMessage() {}

func (x *StartSmsLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSmsLoginResponse.ProtoReflect.Descriptor instead.
func (*StartSmsLoginResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *StartSmsLoginResponse) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *StartSmsLoginResponse) GetExpiresInSeconds() uint32 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

type CompleteSmsLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	ClientType    string                 `protobuf:"bytes,3,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"` // web | ios | android
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteSmsLoginRequest) Reset() {
	*x = CompleteSmsLoginRequest{}
	mi := &file_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteSmsLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteSmsLoginRequest) ProtoMessage() {}

func (x *CompleteSmsLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteSmsLoginRequest.ProtoReflect.Descriptor instead.
func (*CompleteSmsLoginRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteSmsLoginRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *CompleteSmsLoginRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CompleteSmsLoginRequest) GetClientType() string {
	if x != nil {
		return x.ClientType
	}
	return ""
}

type CompleteSmsLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteSmsLoginResponse) Reset() {
	*x = CompleteSmsLoginResponse{}
	mi := &file_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteSmsLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteSmsLoginResponse) ProtoMessage() {}

func (x *CompleteSmsLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteSmsLoginResponse.ProtoReflect.Descriptor instead.
func (*CompleteSmsLoginResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *CompleteSmsLoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *CompleteSmsLoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *CompleteSmsLoginResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_user_v1_user_proto protoreflect.FileDescriptor

const file_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x12user/v1/user.proto\x12\x0eyunmao.user.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"phone_hash\x18\x03 \x01(\tR\tphoneHash\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"5\n" +
	"\x14StartSmsLoginRequest\x12\x1d\n" +
	"\n" +
	"phone_e164\x18\x01 \x01(\tR\tphoneE164\"h\n" +
	"\x15StartSmsLoginResponse\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12,\n" +
	"\x12expires_in_seconds\x18\x02 \x01(\rR\x10expiresInSeconds\"q\n" +
	"\x17CompleteSmsLoginRequest\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1f\n" +
	"\vclient_type\x18\x03 \x01(\tR\n" +
	"clientType\"\x8c\x01\n" +
	"\x18CompleteSmsLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12(\n" +
	"\x04user\x18\x03 \x01(\v2\x14.yunmao.user.v1.UserR\x04user\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\x93\x02\n" +
	"\vUserService\x12\\\n" +
	"\rStartSmsLogin\x12$.yunmao.user.v1.StartSmsLoginRequest\x1a%.yunmao.user.v1.StartSmsLoginResponse\x12e\n" +
	"\x10CompleteSmsLogin\x12'.yunmao.user.v1.CompleteSmsLoginRequest\x1a(.yunmao.user.v1.CompleteSmsLoginResponse\x12?\n" +
	"\aGetUser\x12\x1e.yunmao.user.v1.GetUserRequest\x1a\x14.yunmao.user.v1.UserB\x9b\x01\n" +
	"\x12com.yunmao.user.v1B\tUserProtoP\x01Z yunmao.live/proto/user/v1;userv1\xa2\x02\x03YUX\xaa\x02\x0eYunmao.User.V1\xca\x02\x0eYunmao\\User\\V1\xe2\x02\x1aYunmao\\User\\V1\\GPBMetadata\xea\x02\x10Yunmao::User::V1b\x06proto3"

var (
	file_user_v1_user_proto_rawDescOnce sync.Once
	file_user_v1_user_proto_rawDescData []byte
)

func file_user_v1_user_proto_rawDescGZIP() []byte {
	file_user_v1_user_proto_rawDescOnce.Do(func() {
		file_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)))
	})
	return file_user_v1_user_proto_rawDescData
}

var file_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_user_v1_user_proto_goTypes = []any{
	(*User)(nil),                     // 0: yunmao.user.v1.User
	(*StartSmsLoginRequest)(nil),     // 1: yunmao.user.v1.StartSmsLoginRequest
	(*StartSmsLoginResponse)(nil),    // 2: yunmao.user.v1.StartSmsLoginResponse
	(*CompleteSmsLoginRequest)(nil),  // 3: yunmao.user.v1.CompleteSmsLoginRequest
	(*CompleteSmsLoginResponse)(nil), // 4: yunmao.user.v1.CompleteSmsLoginResponse
	(*GetUserRequest)(nil),           // 5: yunmao.user.v1.GetUserRequest
	(*timestamppb.Timestamp)(nil),    // 6: google.protobuf.Timestamp
}
var file_user_v1_user_proto_depIdxs = []int32{
	6, // 0: yunmao.user.v1.User.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: yunmao.user.v1.CompleteSmsLoginResponse.user:type_name -> yunmao.user.v1.User
	1, // 2: yunmao.user.v1.UserService.StartSmsLogin:input_type -> yunmao.user.v1.StartSmsLoginRequest
	3, // 3: yunmao.user.v1.UserService.CompleteSmsLogin:input_type -> yunmao.user.v1.CompleteSmsLoginRequest
	5, // 4: yunmao.user.v1.UserService.GetUser:input_type -> yunmao.user.v1.GetUserRequest
	2, // 5: yunmao.user.v1.UserService.StartSmsLogin:output_type -> yunmao.user.v1.StartSmsLoginResponse
	4, // 6: yunmao.user.v1.UserService.CompleteSmsLogin:output_type -> yunmao.user.v1.CompleteSmsLoginResponse
	0, // 7: yunmao.user.v1.UserService.GetUser:output_type -> yunmao.user.v1.User
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_user_v1_user_proto_init() }
func file_user_v1_user_proto_init() {
	if File_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_user_proto_goTypes,
		DependencyIndexes: file_user_v1_user_proto_depIdxs,
		MessageInfos:      file_user_v1_user_proto_msgTypes,
	}.Build()
	File_user_v1_user_proto = out.File
	file_user_v1_user_proto_goTypes = nil
	file_user_v1_user_proto_depIdxs = nil
}
